export interface BadgeData {
  id: string;
  badgeName: string;
  category: string;
  difficultyLevel: string;
  estimatedCredits: number;
  estimatedHours: number;
  prerequisites: string;
  learningPath: string;
}

const rawBadges = [
  {name:'Analyze BigQuery Data in Connected Sheets',cat:'Analytics',diff:'Easy',credits:3,hours:3},
  {name:'Analyze Images with the Cloud Vision API',cat:'AI',diff:'Easy',credits:3,hours:3},
  {name:'Analyze Sentiment with Natural Language API',cat:'AI',diff:'Easy',credits:3,hours:3},
  {name:'App Building with AppSheet',cat:'Application Development',diff:'Easy',credits:3,hours:4},
  {name:'Build a Website on Google Cloud',cat:'Application Development',diff:'Easy',credits:3,hours:4},
  {name:'Cloud Speech API: 3 Ways',cat:'AI',diff:'Easy',credits:3,hours:3},
  {name:'Create and Manage Cloud SQL for PostgreSQL Instances',cat:'Data',diff:'Easy',credits:3,hours:4},
  {name:'Derive Insights from BigQuery Data',cat:'Analytics',diff:'Easy',credits:3,hours:4},
  {name:'Develop AI-Powered Prototypes in Google AI Studio',cat:'AI',diff:'Easy',credits:3,hours:4},
  {name:'Develop with Apps Script and AppSheet',cat:'Application Development',diff:'Easy',credits:3,hours:4},
  {name:'Explore Generative AI with the Gemini API in Vertex AI',cat:'AI',diff:'Easy',credits:3,hours:4},
  {name:'Get Started with API Gateway',cat:'APIs',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Cloud Storage',cat:'Infrastructure',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Dataplex',cat:'Data',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Eventarc',cat:'Application Development',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Google Workspace Tools',cat:'Application Development',diff:'Easy',credits:2,hours:2},
  {name:'Get Started with Looker',cat:'Analytics',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Pub/Sub',cat:'Data',diff:'Easy',credits:3,hours:3},
  {name:'Get Started with Sensitive Data Protection',cat:'Security',diff:'Easy',credits:3,hours:3},
  {name:'Kickstarting Application Development with Gemini Code Assist',cat:'Application Development',diff:'Easy',credits:3,hours:4},
  {name:'Monitor and Manage Google Cloud Resources',cat:'Infrastructure',diff:'Easy',credits:3,hours:3},
  {name:'Monitoring in Google Cloud',cat:'DevOps',diff:'Easy',credits:3,hours:3},
  {name:'Networking Fundamentals on Google Cloud',cat:'Networking',diff:'Easy',credits:3,hours:4},
  {name:'Prepare Data for Looker Dashboards and Reports',cat:'Analytics',diff:'Easy',credits:3,hours:4},
  {name:'Prepare Data for ML APIs on Google Cloud',cat:'AI',diff:'Easy',credits:3,hours:4},
  {name:'Prompt Design in Vertex AI',cat:'AI',diff:'Easy',credits:3,hours:3},
  {name:'Set Up a Google Cloud Network',cat:'Networking',diff:'Easy',credits:3,hours:3},
  {name:'Set Up an App Dev Environment on Google Cloud',cat:'Application Development',diff:'Easy',credits:3,hours:3},
  {name:'Share Data Using Google Data Cloud',cat:'Data',diff:'Easy',credits:3,hours:3},
  {name:'Store, Process, and Manage Data on Google Cloud - Console',cat:'Infrastructure',diff:'Easy',credits:3,hours:4},
  {name:'Tag and Discover BigLake Data',cat:'Data',diff:'Easy',credits:3,hours:3},
  {name:'The Basics of Google Cloud Compute',cat:'Infrastructure',diff:'Easy',credits:2,hours:2},
  {name:'Use APIs to Work with Cloud Storage',cat:'APIs',diff:'Easy',credits:3,hours:3},
  {name:'Use Functions, Formulas, and Charts in Google Sheets',cat:'Application Development',diff:'Easy',credits:2,hours:2},
  {name:'Use Machine Learning APIs on Google Cloud',cat:'AI',diff:'Easy',credits:3,hours:4},
  {name:'Using the Google Cloud Speech API',cat:'AI',diff:'Easy',credits:3,hours:3},
  {name:'Analyze Speech and Language with Google APIs',cat:'AI',diff:'Medium',credits:5,hours:5},
  {name:'App Engine: 3 Ways',cat:'Application Development',diff:'Medium',credits:5,hours:5},
  {name:'Automate Data Capture at Scale with Document AI',cat:'AI',diff:'Medium',credits:5,hours:6},
  {name:'Build Google Cloud Infrastructure for AWS Professionals',cat:'Infrastructure',diff:'Medium',credits:5,hours:6},
  {name:'Build Infrastructure with Terraform on Google Cloud',cat:'DevOps',diff:'Medium',credits:5,hours:6},
  {name:'Build LookML Objects in Looker',cat:'Analytics',diff:'Medium',credits:5,hours:5},
  {name:'Build a Data Warehouse with BigQuery',cat:'Data',diff:'Medium',credits:5,hours:6},
  {name:'Build a Smart Cloud Application with Vibe Coding and MCP',cat:'Application Development',diff:'Medium',credits:5,hours:5},
  {name:'Cloud Run Functions: 3 Ways',cat:'Application Development',diff:'Medium',credits:5,hours:5},
  {name:'Configure Service Accounts and IAM Roles for Google Cloud',cat:'Security',diff:'Medium',credits:5,hours:5},
  {name:'Create ML Models with BigQuery ML',cat:'AI',diff:'Medium',credits:5,hours:6},
  {name:'Create a Secure Data Lake on Cloud Storage',cat:'Security',diff:'Medium',credits:5,hours:6},
  {name:'Create a Streaming Data Lake on Cloud Storage',cat:'Data',diff:'Medium',credits:5,hours:6},
  {name:'Create and Manage Bigtable Instances',cat:'Data',diff:'Medium',credits:5,hours:5},
  {name:'Create and Manage Cloud Spanner Instances',cat:'Data',diff:'Medium',credits:5,hours:5},
  {name:'Develop Gen AI Apps with Gemini and Streamlit',cat:'AI',diff:'Medium',credits:5,hours:6},
  {name:'Develop Serverless Applications on Cloud Run',cat:'Application Development',diff:'Medium',credits:5,hours:6},
  {name:'Develop Serverless Apps with Firebase',cat:'Application Development',diff:'Medium',credits:5,hours:6},
  {name:'Develop Your Google Cloud Network',cat:'Networking',diff:'Medium',credits:5,hours:6},
  {name:'Enhance Gemini Model Capabilities',cat:'AI',diff:'Medium',credits:5,hours:6},
  {name:'Implement CI/CD Pipelines on Google Cloud',cat:'DevOps',diff:'Medium',credits:5,hours:6},
  {name:'Implement Cloud Security Fundamentals on Google Cloud',cat:'Security',diff:'Medium',credits:5,hours:5},
  {name:'Implement DevOps Workflows in Google Cloud',cat:'DevOps',diff:'Medium',credits:5,hours:6},
  {name:'Implement Load Balancing on Compute Engine',cat:'Networking',diff:'Medium',credits:5,hours:5},
  {name:'Implementing Cloud Load Balancing for Compute Engine',cat:'Networking',diff:'Medium',credits:5,hours:5},
  {name:'Integrate BigQuery Data and Google Workspace using Apps Script',cat:'Analytics',diff:'Medium',credits:5,hours:5},
  {name:'Manage Data Models in Looker',cat:'Analytics',diff:'Medium',credits:5,hours:5},
  {name:'Migrate MySQL Data to Cloud SQL Using Database Migration Service',cat:'Data',diff:'Medium',credits:5,hours:5},
  {name:'Monitor and Log with Google Cloud Observability',cat:'DevOps',diff:'Medium',credits:5,hours:5},
  {name:'Optimize Costs for Google Kubernetes Engine',cat:'DevOps',diff:'Medium',credits:5,hours:5},
  {name:'Perform Predictive Data Analysis in BigQuery',cat:'Analytics',diff:'Medium',credits:5,hours:6},
  {name:'Privileged Access with IAM',cat:'Security',diff:'Medium',credits:5,hours:5},
  {name:'Secure BigLake Data',cat:'Security',diff:'Medium',credits:5,hours:5},
  {name:'Store, Process, and Manage Data on Google Cloud - Command Line',cat:'Infrastructure',diff:'Medium',credits:5,hours:5},
  {name:'Streaming Analytics into BigQuery',cat:'Analytics',diff:'Medium',credits:5,hours:6},
  {name:'Build Custom Processors with Document AI',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Build Real World AI Applications with Gemini and Imagen',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Build a Data Mesh with Dataplex',cat:'Data',diff:'Hard',credits:7,hours:7},
  {name:'Build a Secure Google Cloud Network',cat:'Networking',diff:'Hard',credits:7,hours:7},
  {name:'Connecting Cloud Networks with NCC',cat:'Networking',diff:'Hard',credits:7,hours:7},
  {name:'Deploy Kubernetes Applications on Google Cloud',cat:'DevOps',diff:'Hard',credits:7,hours:8},
  {name:'Deploy and Manage Apigee X',cat:'APIs',diff:'Hard',credits:7,hours:8},
  {name:'Designing Network Security in Google Cloud',cat:'Security',diff:'Hard',credits:7,hours:7},
  {name:'Detect Manufacturing Defects Using Visual Inspection AI',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Develop and Secure APIs with Apigee X',cat:'APIs',diff:'Hard',credits:7,hours:8},
  {name:'Discover and Protect Sensitive Data Across Your Ecosystem',cat:'Security',diff:'Hard',credits:7,hours:7},
  {name:'Engineer Data for Predictive Modeling with BigQuery ML',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Implement Multimodal Vector Search with BigQuery',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG',cat:'AI',diff:'Hard',credits:7,hours:8},
  {name:'Manage Kubernetes in Google Cloud',cat:'DevOps',diff:'Hard',credits:7,hours:8},
  {name:'Mitigate Threats and Vulnerabilities with Security Command Center',cat:'Security',diff:'Hard',credits:7,hours:7},
  {name:'Protect Cloud Traffic with Chrome Enterprise Premium Security',cat:'Security',diff:'Hard',credits:7,hours:7},
  {name:'Secure Software Delivery',cat:'DevOps',diff:'Hard',credits:7,hours:7},
  {name:'Analyze and Reason on Multimodal Data with Gemini',cat:'AI',diff:'Advanced',credits:9,hours:8},
  {name:'Build and Deploy Machine Learning Solutions on Vertex AI',cat:'AI',diff:'Advanced',credits:9,hours:9},
  {name:'Cloud Architecture: Design, Implement, and Manage',cat:'Infrastructure',diff:'Advanced',credits:9,hours:10},
  {name:'Deploy Multi-Agent Architectures',cat:'AI',diff:'Advanced',credits:9,hours:9},
  {name:'Google DeepMind: Train A Small Language Model',cat:'AI',diff:'Advanced',credits:9,hours:10},
];

export const initialBadges: BadgeData[] = rawBadges.map(b => ({
  id: b.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  badgeName: b.name,
  category: b.cat,
  difficultyLevel: b.diff,
  estimatedCredits: b.credits,
  estimatedHours: b.hours,
  prerequisites: "None",
  learningPath: "General",
}));
